"""init

Revision ID: 607f08ce2ae6
Revises: 
Create Date: 2022-12-08 20:45:49.865821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607f08ce2ae6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
